server:
  port: 8000

spring:
  application:
    name: part2

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
