version: '3.8'

volumes:
  postgres-data:

services:
  app:
    container_name: java
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: postgresdb2
        POSTGRES_PORT: 5432

    ports:
      - 8000:8000
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    depends_on: 
      - db

  db:
    container_name: postgresdb2
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
